/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        primary: '#3525cd',
        'primary-container': '#4f46e5',
        'on-primary': '#ffffff',
        'on-primary-container': '#dad7ff',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        'inverse-primary': '#c3c0ff',

        secondary: '#4e45d5',
        'secondary-container': '#6860ef',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#e3dfff',
        'secondary-fixed-dim': '#c3c0ff',
        'on-secondary-fixed': '#100069',
        'on-secondary-fixed-variant': '#372abf',

        tertiary: '#7e3000',
        'tertiary-container': '#a44100',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffd2be',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb695',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7b2f00',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        surface: '#fcf8ff',
        'surface-dim': '#dcd8e5',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#f0ecf9',
        'surface-container-high': '#eae6f4',
        'surface-container-highest': '#e4e1ee',
        'on-surface': '#1b1b24',
        'on-surface-variant': '#464555',
        'inverse-surface': '#302f39',
        'inverse-on-surface': '#f3effc',

        outline: '#777587',
        'outline-variant': '#c7c4d8',
        'surface-tint': '#4d44e3',
        'surface-variant': '#e4e1ee',
        background: '#fcf8ff',
        'on-background': '#1b1b24',
      },
      fontFamily: {
        sans: ['Poppins', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'unit-xs': '0.25rem',
        'unit-sm': '0.5rem',
        'unit-md': '1rem',
        'unit-lg': '1.5rem',
        'unit-xl': '2.5rem',
        gutter: '1.5rem',
        'card-gap': '1.5rem',
        'container-padding': '2rem',
        'sidebar-width': '280px',
      },
    },
  },
  plugins: [],
};
