/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx}', './public/index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Light Mode Premium Design System
        'surface-container': '#f1f5f9',
        'surface-dim': '#f8fafc',
        'on-secondary-fixed': '#0f172a',
        'primary-fixed-dim': '#3b82f6',
        'outline-variant': '#e2e8f0',
        'error-container': '#fef2f2',
        'background': '#f8fafc',
        'on-tertiary-fixed': '#334155',
        'inverse-primary': '#3b82f6',
        'secondary-fixed': '#2563eb',
        'surface-container-highest': '#cbd5e1',
        'outline': '#94a3b8',
        'tertiary-fixed-dim': '#fb923c',
        'on-error-container': '#991b1b',
        'surface-bright': '#ffffff',
        'secondary-fixed-dim': '#3b82f6',
        'on-surface': '#0f172a',
        'surface-container-low': '#f8fafc',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#f1f5f9',
        'on-tertiary-container': '#334155',
        'on-secondary-container': '#0f172a',
        'surface-container-high': '#e2e8f0',
        'on-primary-container': '#1e40af',
        'on-background': '#0f172a',
        'primary': '#2563eb',
        'tertiary': '#fb923c',
        'primary-container': '#2563eb',
        'on-surface-variant': '#475569',
        'on-primary': '#ffffff',
        'inverse-surface': '#0f172a',
        'error': '#ef4444',
        'tertiary-fixed': '#ffdbcc',
        'on-primary-fixed-variant': '#2563eb',
        'surface-variant': '#f1f5f9',
        'on-secondary-fixed-variant': '#3b82f6',
        'on-tertiary-fixed-variant': '#fb923c',
        'on-error': '#ffffff',
        'primary-fixed': '#2563eb',
        'on-secondary': '#ffffff',
        'surface': '#f8fafc',
        'surface-tint': '#2563eb',
        'inverse-on-surface': '#ffffff',
        'on-primary-fixed': '#ffffff',
        'secondary-container': '#eff6ff',
        'secondary': '#2563eb',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'unit-xl': '2.5rem',
        'unit-xs': '0.25rem',
        'unit-sm': '0.5rem',
        'unit-md': '1rem',
        'gutter': '1.5rem',
        'unit-lg': '1.5rem',
        'container-padding': '2rem',
        'card-gap': '1.5rem',
        'sidebar-width': '280px',
        '18': '4.5rem',   // bottom nav height
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      boxShadow: {
        'custom': '0px 10px 30px rgba(0, 0, 0, 0.03)',
        'custom-lg': '0px 20px 50px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
};
